all:
	gcc -I../include normal.c -o normal -lm
	gcc -I../include lognormal.c -o lognormal -lm
	gcc -I../include exponential.c -o exponential -lm

clean:
	rm -f normal
	rm -f lognormal
	rm -f exponential
